language: go

go:
 - 1.8

go_import_path: github.com/specialedge/hangar-api

install:
  - go get
  - go get github.com/golang/lint/golint 

script:
 - go test -v ./...    
 - golint -set_exit_status $(go list ./...) 
