language: go

go:
 - 1.8

go_import_path: github.com/specialedge/hangar-api

install:
  - go get github.com/gorilla/mux
  - go get github.com/cavaliercoder/grab
  - go get github.com/sirupsen/logrus

script:
 - go test -v ./...    
 - golint -set_exit_status $(go list ./...) 