language: go

go:
 - 1.8

go_import_path: github.com/specialedge/hangar-api

install:
  - go get github.com/gorilla/mux
  - go get github.com/cavaliercoder/grab
  - go get github.com/sirupsen/logrus
  - go get github.com/golang/lint/golint 
  - go get github.com/common-nighthawk/go-figure                       

script:
 - go test -v $(go list ./... | grep -v /vendor/)
 - golint -set_exit_status $(go list ./... | grep -v /vendor/) 
